= Table of Contents
:toc:
:toc-title: 

== About
This document describes the organisation of the ToeBiters project.

== Workdays and meetings

==== Workdays
Every monday and wednesday the team has workdays in the lab. They start at 17:15. Check the calendar to see if a workday is scheduled or not.

==== Meetings
Every tuesday a scheduled management meeting takes place at 12:15. Everyone is welcome but only management has to be there.

== Roles and responsibilites
All roles are fluid; role owners can change during the project.

=== Everyone
- Is responsible to have notifications enabled on Discord and Github.
- Actively engage within their team to achieve the team's goals.
- Reports to the team if they can't show up to a work day or meeting.

=== Team lead
- Responsible for ensuring the team has defined work days.
- Responsible for dividing the work within the team.
- Ensure that development-related routines are followed.
- Acts as the contact person between the project/tech-lead and the team.

=== Treasurer
- Responsible for creating and adhering to a budget.

=== Public relations
- Responsible for events and marketing.

=== Sponsorship coordinator
- Responsible for building relationships with new and existing sponsors.

=== Team builder
- Responsible for organising team-wide activities during the project (e.g., social gatherings).

=== Organiser
- Responsible for managing the project's shared platforms (Github, Discord, Sharepoint, Calendar...).
- Ensure routines related to these platforms are followed.

=== Tech lead
- Works closely with the project lead and team leads.
- Responsible for having a long-term development plan and following it.

=== Project lead
- Works closely with the tech lead.
- Responsible for having a long-term project plan and following it.
- Ensures the project survives generational changes.

== Teams
Team membership is flexible, allowing for team switches or working in multiple teams.

=== Software
Main area encompassing all software-related aspects.

=== Hardware
Main area encompassing all hardware-related aspects.

=== Management
Main area encompassing all management-related aspects. The project leader is the team lead for this team.

- Marketing  
- Sponsorships  
- Budget  
- Organisation  
- Qualification planning for competitions  
- Travel planning for competitions  

== Platforms
The following platforms are used throughout the project.

=== Github
Forum, issue tracking, milestones, (open) documentation.

=== Discord
Ephemeral chat for quick communication, github notifications.

=== Sharepoint
Private documents (ex. meeting protocols, members list, budget...)

=== Calendar
Group activities, milestones, meetings...